# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base
components:
# - components/cymbal-branding
# - components/google-cloud-operations
# - components/memorystore
# - components/network-policies
# - components/non-public-frontend
# - components/service-accounts
# - components/alloydb
# - components/single-shared-session
# - components/spanner
# - components/service-mesh-istio
# - components/without-loadgenerator
# These must be run last and in this order
# - components/container-images-tag
# - components/container-images-tag-suffix
# - components/container-images-registry

namespace: microservices-demo

images:
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice
    newName: main.repository.ext.icrc.org/damienh/microservices-demo/adservice
    newTag: latest
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice
    newName: main.repository.ext.icrc.org/damienh/microservices-demo/cartservice
    newTag: latest
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice
    newName: main.repository.ext.icrc.org/damienh/microservices-demo/checkoutservice
    newTag: latest
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/currencyservice
    newName: main.repository.ext.icrc.org/damienh/microservices-demo/currencyservice
    newTag: latest
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice
    newName: main.repository.ext.icrc.org/damienh/microservices-demo/emailservice
    newTag: latest
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/frontend
    newName: main.repository.ext.icrc.org/damienh/microservices-demo/frontend
    newTag: latest
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/loadgenerator
    newName: main.repository.ext.icrc.org/damienh/microservices-demo/loadgenerator
    newTag: latest
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice
    newName: main.repository.ext.icrc.org/damienh/microservices-demo/paymentservice
    newTag: latest
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice
    newName: main.repository.ext.icrc.org/damienh/microservices-demo/productcatalogservice
    newTag: latest
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/recommendationservice
    newName: main.repository.ext.icrc.org/damienh/microservices-demo/recommendationservice
    newTag: latest
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/shippingservice
    newName: main.repository.ext.icrc.org/damienh/microservices-demo/shippingservice
    newTag: latest
  - name: busybox:latest
    newName: main.repository.ext.icrc.org/busybox:latest
    newTag: latest
  - name: redis:alpine
    newName: main.repository.ext.icrc.org/redis:alpine
    newTag: latest
